### ISSUE TITLE
pass parameters to do_beamforming

### ISSUE THREAD

**Issue by great-thoughts** [xanguera/BeamformIt#10]
I want to change the result_dir (-o) and the print_level. for that I am doing:
`./do_beamforming.sh -o /Users/data/ /Users/data2/ out
`this is what I am getting:
`Usage is: ./BeamformIt/do_beamforming.sh audio_source_dir output_name`

**Comment by xanguera** [comment]
To change the default parameters currently used in the do_beamforming.sh helper script you will need to either call BeamformIt directly from command line or modify that script.
