### ISSUE TITLE
recommended min/max audio length

### ISSUE THREAD

**Issue by great-thoughts** [xanguera/BeamformIt#11]
I am using beamformit on long recordings (1-3hrs). I would like to perform audio processing on chunks of processing for memory issues. I want to know is there any recommendations on the minimum and the maximum length of the audio needed for the beamformit to operate optimally.

**Comment by xanguera** [comment]
Hi,
personally I would just run it with the whole 3h of audio, unless you really have many channels and it does not fit in memory. In such case, just split it in pieces that fit in your memory, but you might have to manually stitch them at the end and might always have some spectrum discontinuity in that position, unless you are careful to split always in silences.
Answering your specific question, there is no optimum minimum/maximum that I could recommend. The only step where the amount of audio available might change results is on the Viterbi steps to refine the TDOAs (if you do them).
