### ISSUE TITLE
quesiton about  --delays_margin

### ISSUE THREAD

**Issue by jingxuan9862** [xanguera/BeamformIt#15]
Hi !  I have a uniform circle arrays with  diameter 80mm and six micrphones, when I set the  delays_margin =0.25 according to the description , the tdoa is wrong . How should I set this parameter?

**Comment by xanguera** [comment]
Hi,
Your circle arrays seem to be pretty standard... What is the exact issue
you are facing?

**Comment by jingxuan9862** [comment]
Mandatory parameters:
  scroll_size: 250
  window_size: 500
  source_dir: 
  show_id: output
  result_dir: ./output/output
  channels_file: ./output/output/channels_file
 Optional parameters:
  uem_file: 
  delay_variance: 5
  ovl_variance: 20
  do_optimum delays: 0
  do_indiv_channels: 0
  output_format: 0
  do_xcorr_reference: 1
  nbest_amount: 4
  reference_channel: 0
  Transition nbest probability: 25.000000
  Percentage of noisy xcorr values: 10.000000
Creating necessary directories
Opening the input channels
Extracting channel information for show output
File 0: /home/jingxuan/BeamformIt/input/person1_scene1_music1_level1_angle3.wav
Filename: //home/jingxuan/BeamformIt/input/person1_scene1_music1_level1_angle3.wav
File //home/jingxuan/BeamformIt/input/person1_scene1_music1_level1_angle3.wav (6 channels) open
Number of channels for file //home/jingxuan/BeamformIt/input/person1_scene1_music1_level1_angle3.wav is 6, creating temporal mono-channel files (wav, floating point)
Opening ./output/output/output_f0_ch0.wav file to write
Opening ./output/output/output_f0_ch1.wav file to write
Opening ./output/output/output_f0_ch2.wav file to write
Opening ./output/output/output_f0_ch3.wav file to write
Opening ./output/output/output_f0_ch4.wav file to write
Opening ./output/output/output_f0_ch5.wav file to write
Opening ./output/output/output_f0_ch0.wav file to read
Opening ./output/output/output_f0_ch1.wav file to read
Opening ./output/output/output_f0_ch2.wav file to read
Opening ./output/output/output_f0_ch3.wav file to read
Opening ./output/output/output_f0_ch4.wav file to read
Opening ./output/output/output_f0_ch5.wav file to read
NumChannels is: 6, sampling rate is 16000
Opening output channels
Opening ./output/output/output.wav file
Marginst** for delays in frames: 0 in ms: 0
Initializing...Total number of delays to be computed: 65
Using an fft window of 8192 points for the window of 8000 points
finished
Setting the reference channel
Determining the reference channel via average xcorr values
Computing the average xcorr between 0 and 1
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?
WARNING!!! no maximum points found in crosscorrelation!!! does your signal contain digital zeros?

**Comment by xanguera** [comment]
It seems indeed that BeamformIt can not find any correlation between
analysis windows, probably due to a delays_margin being too small.
In fact, note that the units of the parameter are in ms, therefore 0.25ms
is a bit too small, I believe.
Try setting it to a higher number, or leave it to the default value of 30,
which works for mostly everyone.
In fact, why don't you just use the default script do_beamforming.sh, which
defines most parameters by default?

X.

**Comment by jingxuan9862** [comment]
when I  use the default script do_beamforming.sh   I get the  toda  as follow

15750 -> 0 0.038009  187 0.039606  -8 0.055974  -48 0.038188  0 1.000000  1 0.041241 
16000 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
16250 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
16500 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
16750 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
17000 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
17250 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
17500 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
17750 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
18000 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
18250 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
18500 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
18750 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 
19000 -> 0 0.042567  187 0.037962  -8 0.045132  -48 0.039409  0 1.000000  -92 0.043918 

but  the diameter of my array is 80mm ,so the maximum delay is 0.235s  corresponding to the 4 sampling points  . so  I think the the tdoa  is wrong . what do you think?

**Comment by xanguera** [comment]
Sorry, I do not understand your point. In the numbers above the maximum
delay you have is 187, which at 16K gives about 0.011s, way below the 0.2s
you indicate. Is there maybe a conversion misunderstanding?

**Comment by jingxuan9862** [comment]
Sorry,  the maximum is  0.235 ms  ,  so the 187 is  unreasonable   .

**Comment by jingxuan9862** [comment]
what I mean is the the diameter of the micrphone array determines the maxinum delay is 0.235ms

**Comment by xanguera** [comment]
187 samples / 16000 samples/second = 0.01168 << 0.235

**Comment by jingxuan9862** [comment]
187 samples / 16000 samples/second = 0.01168 s >>0.235 ms

**Comment by jingxuan9862** [comment]
0.08m/340 m/s= 0.235  ms

**Comment by xanguera** [comment]
My apologies! multitasking is not good for anyone :)

You are right, the numbers do not match. My possible explanation is that
your recording system might not start all channels at the same time. It
happened a long time ago with ICSI meeting corpus.
Maybe open both signals in an audio editor tool and manually check whether
the 0.011s make sense.

X.

**Comment by xanguera** [comment]
Hi,
any news on this? did you find the discrepancy?

X.

**Comment by jingxuan9862** [comment]
Hi,
 I find that  there are  silence segments in the recording. the tdoa in that segments are unreasonable.

**Comment by xanguera** [comment]
I see, so the whole issue came from a silence region :)
Yes, whenever there is no signal to compare the tool is not able to correctly find the right TDOA.
