### ISSUE TITLE
BeamformIt output file

### ISSUE THREAD

**Issue by aishwaryjoshi31** [xanguera/BeamformIt#16]
Hey, I am new to the beamformit tool and I am running tool using the basic way. In the output I have .del, .del2 and .weat file. Can you tell me where are actually the tdoa features, I know that .del contain best tdoa delays for each segment. So are those delays actually the tdoa features or have to use some weighing to generate feature using .weat file is my question? ?

**Comment by xanguera** [comment]
The filtered tdoa features are in .del file. These are the delays that are actually applied to the signals to merge them, not the raw TDOA that the system returns. To get that you will need to disable all postprocessing done after TDOA computation.
