### ISSUE TITLE
I can enhance the sound in a certain direction 

### ISSUE THREAD

**Issue by sunjunlishi** [xanguera/BeamformIt#18]
I can enhance the sound in a certain direction ,using your method,and how  input 
parameter

**Comment by xanguera** [comment]
Hi,
you have several sample config files in
https://github.com/xanguera/BeamformIt/tree/master/cfg-files
In addition, the script
https://github.com/xanguera/BeamformIt/blob/master/do_beamforming.sh can do
what you want if you put the wav files all in a single directory.

**Comment by sunjunlishi** [comment]
thank you  very very much,i will  have  a try

**Comment by sunjunlishi** [comment]
There's almost no change; your parameters don't have the microphone spacing; and there's no parameter to increase the input in one direction 
![qq 20171028110439](https://user-images.githubusercontent.com/11845664/32130710-10ce6352-bbd0-11e7-84f2-fc0e4d70bc9f.png)

**Comment by sunjunlishi** [comment]
![qq 20171028110439](https://user-images.githubusercontent.com/11845664/32130771-25245072-bbd1-11e7-8f26-49746be8774d.png)

**Comment by xanguera** [comment]
Hi,
BeamformIt is not designed to adapt to any particular configuration, but to
obtain the best possible output signal given an unknown microphone setting.
If you need to configure the spacing, directionality, etc... you should
better look for other tools, or implement some other algorithm that allows
such setup.

**Comment by sunjunlishi** [comment]
Can you provide a wav  file to see how powerful it is?

**Comment by sunjunlishi** [comment]
fixed beamforming
