### ISSUE TITLE
Can this system be used directly after downloading?

### ISSUE THREAD

**Issue by XiaoyuGuo123** [xanguera/BeamformIt#20]
Can the system process data in real time?
Does this system have a version of C?

**Comment by xanguera** [comment]
Hi,
currently BeamformIt is implemented as a batch process, not for online use.
You should be able to implement a simple version of it for online usage
using plain delay&sum.

BeamformIt is implemented in C++, with lots of C in there. Are you in need
of C for some specific implementation or target architecture?
