### ISSUE TITLE
How closely aligned do audio files have to be for this to work?

### ISSUE THREAD

**Issue by zaptrem** [xanguera/BeamformIt#22]
I’m trying to work with a similar set of recordings to the example in the README (a bunch of random microphones recording separately in a conference room. However, they all started recording and stopped recording at different times. Do I need to align the files somehow so they all start and stop at the same time or does the BeamformIt simple method do that for me?

Thanks!

**Comment by xanguera** [comment]
Beamformit has some parameters that allow it to align recordings that are
not very well aligned to start with. This was built thinking of initial
ICSI meeting room recordings where hardware problems created some start
time differences. These are though quite small and I do not know how much
you can stretch it to work on a case where your misalignments are too big.
The method that is used should potentially make it (I recall I was sampling
windows of audio across the whole recording to get an average misalignment
between channels) but it will definitely work much easier if you can
initially align them yourself.

**Comment by zaptrem** [comment]
I can probably align them within a second of each other by taking down the real time before starting each recording. Is there any way I can grab the output of your alignment algorithm before the beamforming begins? I want to compare accuracy with other algorithms but there are no open source audio alignment scripts that exist (as far as my searches have found).

**Comment by xanguera** [comment]
You can easily print them out from inside the code where they get computed. There is also an output file with the TDOA values used in the sum.
