### ISSUE TITLE
Question : is it possible to spatially filter audio using a microphone array?

### ISSUE THREAD

**Issue by pfeatherstone** [xanguera/BeamformIt#25]
I have a https://wiki.seeedstudio.com/ReSpeaker_Mic_Array_v2.0/ microphone array.
Is it possible, using this repository, given the microphone array topology, to spatially filter the audio channels in a particular direction?

**Comment by xanguera** [comment]
No, I am afraid. BeamformIt is topology agnostic and is used to produce a
good single channel audio, not for source separation.

**Comment by pfeatherstone** [comment]
Thank you.

**Comment by pfeatherstone** [comment]
@xanguera do you know of a good way to do source separation, preferably in C or C++? There is https://github.com/introlab/odas but it's not very easy or predictable to use.

**Comment by xanguera** [comment]
No, I am sorry.
