### ISSUE TITLE
.del files format explained

### ISSUE THREAD

**Issue by ChrisSpraaklab** [xanguera/BeamformIt#28]
Hi @xanguera,

Thanks for BeamformIt, it works really well for my application. I do however have one question: could you explain the format of the .del files? What do the values mean? I am trying to use that data as a feature for diarization. Example of one row: 
```0 -> 0 1.000000  0 0.126987  4 0.125331  0 0.139378  0 0.175643  0 1.000000  -2 0.111881  -4 0.139887  0 1.000000  0 0.163803  0 0.157673  0 0.124941  2 0.124990  0 0.106618  0 0.120836  0 0.124682```
There are 16 channels in my audio, and I see that reprented in this .del file. I get that the first number indicates a window of 250 ms. What I don't understand however are the values ```[0, 2, 4, -4]``` in front of every decimal value. I am guessing the decimal value is the delay info?

Thanks in advance.

**Comment by xanguera** [comment]
Hi,
you are welcome.
As per the documentation: "It contains a delay for each scroll segment and
their GCC-PHAT values". This means that the integer value is the optimum
time delay applied to each channel and the floating point value is the
correlation strength with the reference channel (i.e. how similar that
piece of audio is to the channel taken as reference).

yours,

Xavier
