### ISSUE TITLE
Any advice on hoe to use beamformit to remove background noise from single channel recording?

### ISSUE THREAD

**Issue by great-thoughts** [xanguera/BeamformIt#8]
For some events I have a single recording. but i still want to use beamformit for the acoustic signal enhancment capabilities. specifically background noise removal based on wiener filter. what i did is i run do_beamforming.sh on a folder with a single recording but the background noise in the output was not removed. Any advice on hoe to use beamformit to remove background noise from single channel recording?

**Comment by xanguera** [comment]
Beamformit _does not_ apply any wiener filtering to the signal [yet]. If you have a single channel, you do not need the tool.
